version: "3.1"

services:
  pg:
    image: docker.io/postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "api"
      POSTGRES_DB: "todos"
  redis:
    image: docker.io/redis:6.2-rc2-alpine3.12
    restart: always
  api:
    build: .
    restart: always
    environment:
      POSTGRES_HOST: "pg:5432"
      POSTGRES_DATABASE: "todos"
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "1234"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: 0
    ports:
      - 3000:3000
